parameters:
    pim_enrich.mass_edit_action.capitalize_values.class: Acme\Bundle\EnrichBundle\MassEditAction\Operation\CapitalizeValues

services:
    pim_enrich.mass_edit_action.capitalize_values:
        public: false
        class: %pim_enrich.mass_edit_action.capitalize_values.class%
        tags:
            -
                name: pim_enrich.mass_edit_action
                alias: capitalize-values
                acl: pim_enrich_product_capitalize_values
                datagrid: product-grid
